#moi_secure:
#    resource: "@moiSecureBundle/Resources/config/routing.yml"
#    prefix:   /



    
login:
    path: /login
    defaults:
        _controller: moiSecureBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

moi_crud_article:
    resource: "@moiCrudBundle/Controller/ArticleController.php"
    type:     annotation